name: Build and Deploy Web Game

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build for Web
        run: |
          emcmake cmake -B build-web -DPLATFORM=Web
          cmake --build build-web
          mkdir release
          cp build-web/sataro.html release/index.html
          cp build-web/sataro.js release/
          cp build-web/sataro.wasm release/
          cp build-web/sataro.data release/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release
